wallpaper { 
    monitor = eDP-1
    path = ~/Documents/Wallpapers/sunset.png
    fit_mode = cover
}

wallpaper {
    monitor = 
    path = ~/Documents/Wallpapers/sunset.png
    fit_mode = cover
}
splash = false
ipc = off
